version: '3'

services:
  nanda_mysql:
    image: mysql:latest
    container_name: nanda_mysql
    environment:
      MYSQL_ROOT_PASSWORD: RedHat123$# 
      MYSQL_DATABASE: nanda_db
      MYSQL_USER: nanda
      MYSQL_PASSWORD: RedHat123$
    volumes:
      - type: volume
        source: compose-volume
        target: /var/lib/mysql
    networks:
      - compose-network
  nanda_php:
    build: 
      dockerfile: ./devops/docker/php.dockerfile
    container_name: nanda_php
    volumes:
      - type: bind
        source: ./
        target: /var/www/html
    networks:
      - compose-network
    depends_on:
      - nanda_mysql
  nanda_nginx:
    image: nginx:latest
    container_name: nanda_nginx
    depends_on:
      - nanda_php
    ports:
      - "8080:80"
    volumes:
      - type: bind
        source: ./
        target: /var/www/html
      - type: bind
        source: ./devops/docker/nginx.conf
        target: /etc/nginx/conf.d/default.conf
    networks:
      - compose-network

volumes:
  compose-volume:

networks:
  compose-network:
    driver: bridge
