name: Deploy modifed laravel project with github actions

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy_laravel:
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v4
       - name: SSH Remote Commands & Deploy laravel project
         uses: appleboy/ssh-action@v1.0.3
         with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.LARAVELGITHUBPRIVATEKEY }}
          script: |
            bash /home/ubuntu/laravel-app.sh
            echo "Deployment of laravel completed successfully"
