name: Deploy dockerized laravel project with github actions

on:
  push:
    branches: [ "docker-compose-githubactions" ]
  pull_request:
    branches: [ "docker-compose--githubactions" ]

jobs:
  deploy_laravel:
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v4
       - name: SSH Remote Commands & Deploy laravel project
         uses: appleboy/ssh-action@v1.0.3
         with:
          host: ${{ secrets.DOCKERIZED_HOST }}
          username: ${{ secrets.DOCKERIZED_USERNAME }}
          key: ${{ secrets.LARAVELGITHUBPRIVATEKEY }}
          script: |
            bash /home/ubuntu/dockerize-laravel.sh
            echo "Deployment of dockerized laravel project completed successfully"
